---
title: "Party Problem Redux"
author: "Bob"
date: "2024-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reproducing the textbook calculations

from [Foundations of Decision Analysis](https://www.amazon.com/Foundations-Decision-Analysis-Global-Howard/dp/129207969X) by Howard & Abbas.

```{r more_libraries, message=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(plotly)
library(igraph)
library(fields)
```

### Kim's decision tree
```
alternatives <- c("Outdoors", "Porch", "Indoors")
weather <- c("Sunshine", "Rain")

prospects <- paste(rep(alternatives, each=2), weather, sep='_')

node_names <- c("START", alternatives, prospects)

node_df <- data.frame( id=seq_along(node_names), name=node_names )

edge_df <- data.frame( from=c(1,1,1,2,2,3,3,4,4), to=c(2,3,4,5,6,7,8,9,10))

g <- graph_from_data_frame(d=edge_df, directed=TRUE, vertices=node_df)
plot(g)

preference_probs <- c(1, 0.95, 0.67, 0.57, 0.32, 0)
dollar_values <- c( 100, 90, 50, 40, 20, 0)
order <- c( 1, 6, 2, 5, 4, 3)

prospect_values <- data.frame(prospects=prospects,
                              preference_probability=preference_probs[order],
                              dollar_value=dollar_values[order])
prospect_values

u_kim <- function(x) (4/3)*(1 - (1/2)**(x/50)) # p220

```


```{r}

# I think we want Jane's sun sensitivity
kim_sun_sensitivity <- function(p){
  list(
    p = p,
    Outdoor = p,
    Porch = 0.95*p + 0.323 * (1 - p),
    Indoor = 0.568*p + 0.667*(1 - p)
  )
}

utility_given_p <- function(p){
  utility <- kim_sun_sensitivity(p)[c('Outdoor', 'Porch', 'Indoor')]
  utility[which.max(utility)]
}



```

```{r figure_13_14}

sensitivity_stats <- function(tpr, fpr, p=0.4){
  tp = p*tpr
  fp = (1-p)*(1-fpr)
  fn = p*(1-tpr)
  tn = (1-p)*fpr
  
  posterior_prob_given_S_predicted = tp/(tp + fp)
  u_S = utility_given_p(posterior_prob_given_S_predicted)
  preposterior_S_predicted = p*tpr + (1 - p)*(1 - fpr)
  
  posterior_prob_given_R_predicted = 1 - tn/(tn + fn)
  u_R = utility_given_p(posterior_prob_given_R_predicted)
  preposterior_R_predicted = p*(1 - tpr) + (1-p)*fpr
  
  u_value_of_experiment = u_S[[1]] * preposterior_S_predicted + u_R[[1]] * preposterior_R_predicted
  
  list(
    `Sensitivity t` = tpr,
    `Specificity f` = fpr,
    `Posterior Prob Given "S" {S|"S",&}` = posterior_prob_given_S_predicted,
    `Best Party Location Given "S"` = names(u_S),
    `u-Value of Party Location Given "S"` = u_S[[1]],
    `Preposterior {"S"|&}` = preposterior_S_predicted,
    `Posterior Prob Given "R" {S|"R",&}` = posterior_prob_given_R_predicted,
    `Best Party Location Given "R"` = names(u_R),
    `u-Value of Party Location Given "R"` = u_R[[1]],
    `Preposterior {"R"|&}` = preposterior_R_predicted,
    `u-Value of Experiment` = u_value_of_experiment
  )
  
}

# sensitivity_stats(0.8, 0.8)

fig_13_14_rows = list( list(0.8, 0.8), list(0.9, 0.7), list(0.7, 0.9), list(0.6, 1.0))

fig_13_14_df <- fig_13_14_rows %>% 
  lapply(function(l) do.call(sensitivity_stats, l)) %>% 
  bind_rows %>% 
  as.data.frame

fig_13_14_df
```


# Plotting images of utility in ROC space (Sensitivity against 1 - Specificity)

```{r roc_at_p}
S <- 100
sensitivities <- specificities <- seq(1/S, 1-(1/S), length.out=S-1)
prevalences <- c(0.4, 0.61, 0.7)

char_matrix_to_int <- function(M){
  matrix(M %>% factor %>% as.integer, nrow=nrow(M), ncol=ncol(M))
}

for (prevalence in prevalences){
  U <- matrix(0, nrow=S, ncol=S) # Utility
  L <- matrix(0, nrow=S, ncol=S) # Location
  for (i in seq_along(sensitivities)){
    sensitivity <- sensitivities[i]
    for (j in seq_along(specificities)){
      specificity <- 1 - specificities[j]
      ss <- sensitivity_stats(sensitivity, specificity, prevalence)
      U[i,j] <- ss[['u-Value of Experiment']]
      L[i,j] <- ss[['Best Party Location Given "S"']]
    }
  }    
  
  run_name <- sprintf("party_problem_roc_bob_%02dpct", floor(prevalence*100))
  
  png(paste0(run_name, '.png'), width=960, height=480)
  
  op <- par(mfrow=c(1,2), oma = c(3,3,4,3))
  
  # max payout is 100 for an outdoor party in the sun
  # the worst best choice payoff is 40 for on the porch in the rain
  image.plot( c(0, sensitivities), c(0, specificities), t(U),
       asp=1, zlim=c(0.62, 0.88), nlevel=32,
       xlab="1 - Specificity", ylab="Sensitivity",
       main=sprintf("Model Utility at P(rain) = %2d%%", as.integer(100*prevalence)))
  
  image.plot(c(0, sensitivities), c(0, specificities), t(L %>% char_matrix_to_int),
       asp=1, nlevel=32,
       xlab="1 - Specificity", ylab="Sensitivity",
       main="Location")

  mtext(sprintf("Prior probability of rain: %0.2f", prevalence), side=3, line=0, outer=TRUE, cex=2)

  mtext("2=Outside 3=Inside 4=Porch", side=4, line=1, outer=TRUE, cex=1.5)
  
  par(op)
  
  dev.off()
}

```
